Mohammed FASE 1 – Datatypes & Tijdstructuur

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
path = Path("../../data/processed/df_v5_clean_final.csv")
df = pd.read_csv(path)
df.head()

    Peildatum        Wijk  AantalInwoners_5  k_0Tot15Jaar_8  k_15Tot25Jaar_9
0  2018-01-01  WK003401               22790            3975             2420
1  2019-01-01  WK003401               22875            3945             2415
2  2020-01-01  WK003401               23275            4005             2485
3  2021-01-01  WK003401               23530            4180             2465
4  2022-01-01  WK003401                1635             175              150

In [5]:
df.shape

(237, 5)

In [6]:
df.columns

Index(['Peildatum', 'Wijk', 'AantalInwoners_5', 'k_0Tot15Jaar_8',
       'k_15Tot25Jaar_9'],
      dtype='str')

In [7]:
df.dtypes

Peildatum             str
Wijk                  str
AantalInwoners_5    int64
k_0Tot15Jaar_8      int64
k_15Tot25Jaar_9     int64
dtype: object

In [8]:
df["Peildatum"] = pd.to_datetime(df["Peildatum"], errors="coerce")
df["Jaar"] = df["Peildatum"].dt.year
df[["Peildatum", "Jaar"]].head()

   Peildatum  Jaar
0 2018-01-01  2018
1 2019-01-01  2019
2 2020-01-01  2020
3 2021-01-01  2021
4 2022-01-01  2022

In [9]:
num_cols = [
    "AantalInwoners_5",
    "k_0Tot15Jaar_8",
    "k_15Tot25Jaar_9"
]
df[["Peildatum", "Jaar"] + num_cols].isna().sum()

Peildatum           0
Jaar                0
AantalInwoners_5    0
k_0Tot15Jaar_8      0
k_15Tot25Jaar_9     0
dtype: int64

In [10]:
df = df.sort_values(["Wijk", "Jaar"])
df[["Wijk", "Jaar"]].head(15)

          Wijk  Jaar
0   WK003401    2018
1   WK003401    2019
2   WK003401    2020
3   WK003401    2021
4   WK003401    2022
5   WK003401    2023
6   WK003401    2024
7   WK003401    2025
8   WK003402    2018
9   WK003402    2019
10  WK003402    2020
11  WK003402    2021
12  WK003402    2022
13  WK003402    2023
14  WK003402    2024

In [11]:
df.duplicated(subset=["Wijk", "Jaar"]).sum()

np.int64(0)

In [12]:
df

,Peildatum,Wijk,AantalInwoners_5,k_0Tot15Jaar_8,k_15Tot25Jaar_9,Jaar
0,2018-01-01,WK003401,22790,3975,2420,2018
1,2019-01-01,WK003401,22875,3945,2415,2019
2,2020-01-01,WK003401,23275,4005,2485,2020
3,2021-01-01,WK003401,23530,4180,2465,2021
4,2022-01-01,WK003401,1635,175,150,2022
...,...,...,...,...,...,...
232,2024-01-01,WK003477,5230,1115,400,2024
233,2025-01-01,WK003477,6135,1300,465,2025
234,2022-01-01,WK003485,90,5,15,2022
235,2023-01-01,WK003485,85,10,10,2023
236,2024-01-01,WK003485,80,5,15,2024

In [13]:
df.to_csv("../../data/processed/df_v6_clean_final.csv", index=False)